# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21b53ac1db4b84e86480d20b2ac5e19a0f65ba66e5bc04a53276582a6746f8a6ff84904c6b4d4e4ce5fd32a589adf2d5535ad1f4effcac59327e509f1b467469

test:
  secret_key_base: aa92dff1725a4419914a162e948ded3ee1339f857108ea3da05812fc5799c72e8e0f0fca4752c6493795908f129bdb657000066d5be3591b4e017db71990b88d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
